// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GetUserRequest struct {
	Id string `json:"id"`
}

type GetUserResponse struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
}
